### PR TITLE
Tokenize PHPDoc param types

### LINKED ISSUE #136: [PHPDoc] Highlight `@param` return types and variable names
The specification of PHPDoc types can be seen here:
https://phpdoc.org/docs/latest/references/phpdoc/types.html

I'm going to try take a stab at this, but I thought I'd file an issue so as to ask some basic questions.
1. Should I be editing 'php.cson' directly? -- is it being generated from somewhere else? It's a complete mess
2. What should I _not_ do? (to avoid getting a PR rejected)

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Tokenizes PHPDoc [types](https://phpdoc.org/docs/latest/references/phpdoc/types.html).

### Alternate Designs

None.

### Benefits

Fancy highlighting for types in PHPDoc.

### Possible Drawbacks

Weird highlighting for some themes?

### Applicable Issues

Closes #136

/cc @kroc: could you maybe try this out and report anything weird/broken you encounter?

### CODE REVIEW

**Comment by 50Wliu** [comment]
Merging - will iterate as necessary.

**Comment by jens1o** [comment]
This does not work for nested classnames, such as `\wcf\data\language\Language`.

For example:
image

**Comment by 50Wliu** [comment]
@jens1o please open a new issue.

**Comment by jens1o** [comment]
@50Wliu Gotcha.

**Pull request merged**
