### PR TITLE
PHP 7.4 updates

### PR DESCRIPTION
**Pull request by KapitanOczywisty**
## Updates for PHP 7.4

New PRs with parts of this.

- [x] Arrow functions #377 
- [x] Numeric literal separator #378 
- [x] Missing operators: spread, exponentiation, null coalescing #379
- [x] Typed properties, anonymous classes, object serialization #380

---
---

All functions are now implemented, you can test and give feedback ;)

For testing I've merged my other pull requests in: [KapitanOczywisty:merge-all](https://github.com/KapitanOczywisty/language-php/tree/merge-all)

For `vscode` you can get preview extension here: 
- [KapitanOczywisty/vscode-php-dev](https://github.com/KapitanOczywisty/vscode-php-dev) or
- [KapitanOczywisty/vscode-php-dev:merge-all](https://github.com/KapitanOczywisty/vscode-php-dev/tree/merge-all) with 2 other pr merged
(Use `Inspect TM Scopes` to check if extension works correctly).

#### Syntax

- [x] Arrow functions [rfc](https://wiki.php.net/rfc/arrow_functions_v2)
  - [x] syntax
  - [x] test spec
- [x] Numeric Literal Separator [rfc](https://wiki.php.net/rfc/numeric_literal_separator)
  - [x] syntax
  - [x] test spec
- [x] Spread Operator in Array Expression [rfc](https://wiki.php.net/rfc/spread_operator_for_array)
  - [x] basic spread syntax (spread is not supported at all)
  - [x] test spec
- [x] Typed Properties 2.0 [rfc](https://wiki.php.net/rfc/typed_properties_v2)
  - [x] syntax
  - [x] test spec
- [x] Null Coalescing Assignment Operator [rfc](https://wiki.php.net/rfc/null_coalesce_equal_operator)
  - [x] syntax
  - [x] test spec
  - [x] +missing Exponentiation Operator

#### Definitions

- [x] weakrefs (already supported) [rfc](https://wiki.php.net/rfc/weakrefs)
- [x] FFI - Foreign Function Interface [rfc](https://wiki.php.net/rfc/ffi)
- [x] Reflection for references [rfc](https://wiki.php.net/rfc/reference_reflection)
- [x] New custom object serialization mechanism [rfc](https://wiki.php.net/rfc/custom_object_serialization)

#### changes prior PHP 7.4 (not updated before)

- [x] `iterable` pseudo-type [rfc](https://wiki.php.net/rfc/iterable)
- [x] anonymous classes [rfc](https://wiki.php.net/rfc/anonymous_classes)
  - [x] syntax
  - [x] test spec (shares most of its syntax with classes)
- [x] Sodium - functions, constants, classes
- [x] Many functions and constants partially added in b2510bc
- [x] Password Hashing - Add constants
- ~~CURL - update constants [current](https://regex101.com/r/WIFVPP/1/) / [proposed regex](https://regex101.com/r/DXn0ip/1)~~
- ~~GD - add constants~~
- ~~LDAP - add constants~~
- ~~PGSQL - add constants~~
- ~~PCNTL - add constants [source](https://github.com/php/php-src/blob/99ce142f6e37e803ce7c0fdaece79b9813c33543/ext/pcntl/pcntl.c#L263)~~

*No more definitions in this pull-request, I'will provide proposition for major update in separate issue*

#### To think about

- ~~`C` syntax inside FFI functions [rfc](https://wiki.php.net/rfc/ffi)~~

### Alternate Designs

`fn` got scope `storage.type.function.php` alternative: `storage.type.fn.php`
`=>` got scope `punctuation.definition.arrow.php` alternative: ??
`_` did **not** get own scope in numbers, if necessary `punctuation.separator.literal.underscore.php` or similar could be added

**Current scopes**

<details><summary><em>Arrow functions</em></summary>
<div>

Test code: `fn($x) => $x;`

0: `fn` scopes: `source.php` `meta.function.closure.php` `storage.type.function.php`
1: `(` scopes: `source.php` `meta.function.closure.php` `punctuation.definition.parameters.begin.bracket.round.php`
2: `$` scopes: `source.php` `meta.function.closure.php` `meta.function.parameters.php` `meta.function.parameter.no-default.php` `variable.other.php` `punctuation.definition.variable.php`
3: `x` scopes: `source.php` `meta.function.closure.php` `meta.function.parameters.php` `meta.function.parameter.no-default.php` `variable.other.php`
4: `)` scopes: `source.php` `meta.function.closure.php` `punctuation.definition.parameters.end.bracket.round.php`
5: ` ` scopes: `source.php` `meta.function.closure.php`
6: `=>` scopes: `source.php` `meta.function.closure.php` `punctuation.definition.arrow.php`
7: ` ` scopes: `source.php`
8: `$` scopes: `source.php` `variable.other.php` `punctuation.definition.variable.php`
9: `x` scopes: `source.php` `variable.other.php`
10: `;` scopes: `source.php` `punctuation.terminator.expression.php`

</div>
</details>

<details><summary><em>Anonymous classes</em></summary>
<div>

Test code: `$a = new class {};`

0: `$` scopes: `source.php` `variable.other.php` `punctuation.definition.variable.php`
1: `a` scopes: `source.php` `variable.other.php`
2: ` ` scopes: `source.php`
3: `=` scopes: `source.php` `keyword.operator.assignment.php`
4: ` ` scopes: `source.php`
5: `new` scopes: `source.php` `meta.class.php` `keyword.other.new.php`
6: ` ` scopes: `source.php` `meta.class.php`
7: `class` scopes: `source.php` `meta.class.php` `storage.type.class.php`
8: ` ` scopes: `source.php` `meta.class.php`
9: `{` scopes: `source.php` `meta.class.php` `punctuation.definition.class.begin.bracket.curly.php`
10: `}` scopes: `source.php` `meta.class.php` `punctuation.definition.class.end.bracket.curly.php`
11: `;` scopes: `source.php` `punctuation.terminator.expression.php`

</div>
</details>

### Benefits

Compatibility with php 7.4

### Possible Drawbacks

none

### Applicable Issues

none

### CODE REVIEW

**Comment by KapitanOczywisty** [comment]
@rsese Like with others - ready for review ;)

**Comment by rsese** [comment]
Hey @KapitanOczywisty!  Thanks again for the contribution - we looked at this one today and I made a bad assumption that 7.4 was already released, sorry about that.  We poked around and see the release date seems to be end of November 2019.

For the language packages we usually wait till the language features are generally available so this isn't something that would be reviewed before then.  

Additionally, with a change as large as this there was a concern about maintenance since there's currently not a lot of PHP expertise on the team right now.  If this was merged, would you be around to help with followup issues related to this PR?

**Comment by KapitanOczywisty** [comment]
@rsese PHP 7.4 is in the Release Candidate stage, so features are fixed by now and only bug fixes will be deployed before full 7.4.0 release. Also there aren't any backward incompatible changes in this patch, no existing test was harmed. Moreover, I've skipped more messy changes for this PR (e.g. constants are a bit outdated and in wrong groups). In my opinion it's safe to merge this PR sooner. If you can merge other two PR before this I would solve conflicts which will probably arise.

> If this was merged, would you be around to help with followup issues related to this PR?

Of course, I'm following this repo, but you can also dm me on slack.

**Comment by KapitanOczywisty** [comment]
@rsese PHP 7.4 is now live :)

**Comment by rsese** [comment]
Thanks for the reminder! :zap:  I'll share this with the maintainers for you.

**Comment by lee-dohm** [comment]
Since this is a _huge_ PR and there are conflicts, would you mind closing this PR and breaking it up into a series of smaller PRs to make it more manageable for our team?

**Comment by KapitanOczywisty** [comment]
@lee-dohm I can split this PR, but this can take me a while. Conflicts are now resolved if meanwhile you would want to go with this anyway. I'm using this in vscode since a few months without any problems.

**Comment by KapitanOczywisty** [comment]
@lee-dohm Made 4 new PRs #377 #378 #379 #380. Other definitions are waiting for merge of these 4.

**Comment by lee-dohm** [comment]
Thanks for the work you've put in on this! I've added the four related PRs to the queue to be reviewed. Since this PR isn't going to be merged in its current form, I'm going to go ahead and close it.

**Pull request closed without merging**
