### PR TITLE
Fixed: Block try...catch now uses \Exception instead of Exception

### PR DESCRIPTION
**Pull request by eliasib13**
This solves #156 issue :)

### CODE REVIEW

**Comment by Ingramz** [comment]
For consistency, `throw` snippet should get the same change.

However in general I have mixed feelings about all of this, but I am not going to say it's by any means bad.

**Comment by 50Wliu** [comment]
> However in general I have mixed feelings about all of this

Can you elaborate?

**Comment by Ingramz** [comment]
I just think it's rather obvious that when using namespaces, you are somewhat supposed to keep track of this yourself. Adding backslash in front to denote the root isn't bad on it's own but catching a generic Throwable/Exception/Error most of the time is. For quick and dirty development I suppose it is ok. The snippets should try to encourage changing the name of Exception class though.

**Comment by 50Wliu** [comment]
> The snippets should try to encourage changing the name of Exception class though.

So are you saying it should be `\\\\$1Exception` instead?

**Comment by Ingramz** [comment]
No, not really. My concern is/was that by making the snippet work, it's not giving user enough incentive to use a better name for the exception that is going to be thrown/caught. I've now concluded that this is something we can't protect against.

The way how certain parts of the snippet are selected is more related to usability of the snippets, it would be better to ask others on this subject.

For instance I would prefer myself if the whole exception name + backslash was selected as a whole and then if I skipped that with tab, it would only highlight the exception name, leaving backslash intact. How the variable name should be selected is hard to tell, maybe like this:
**\Exception $e**
\\**Exception $e**
\\**Exception** $e
\Exception **$e**

This should allow overwriting as soon as you have reached the desired level, but this is not the only solution.

**Comment by joehoyle** [comment]
Im not sure this is a good default, in a file that doesn't have  namespace, the `\` in unnecessary - and even in a file that _does_ have a namespace, I'd say typically it's best private to `use` the `Exception`  class at the top of the file. 

Personally, I don't think the snippet needs to work in every context, just as I can't use a try catch snippet in plenty of other contexts, it's not the job of the snippets to be contextual like that.

**Comment by AlexNodex** [comment]
@joehoyle While the `\` is unnecessary in files that don't have namespaces, it does no harm whatsoever. It visually promotes to the programmer that it's a root `Exception`. Namespaced files are much more prevelant than non namespaced files and in my experience it's good to know what's in the root namespace and what isn't.

**Pull request merged**
